### ISSUE TITLE
Support for hosted HTTPS

### ISSUE THREAD

**Issue by opsydev** [djonsson/jenkins-atlassian-theme#48]
It would be great if hosted HTTPS was available since it takes the hassle out of upgrading. It is possible to use something like https://cdnjs.com/ to provide full hosting support.

**Comment by ssbarnea** [comment]
Correct me if I am wrong but my impression is that this bug is not solved. 

If I put HTTPS instead of HTTP on the URLs from the installation instructions it will not work.

Also the documentation should show the HTTPS or both.

**Comment by rtgibbons** [comment]
This has bee updated on the Readme in Develop - https://github.com/djonsson/jenkins-atlassian-theme/blob/develop/README.md
