### ISSUE TITLE
failed/success icons not working

### ISSUE THREAD

**Issue by jacksoncage** [djonsson/jenkins-atlassian-theme#52]
http://cl.ly/image/0U0z2d2H0w3Q

Looks like it's changed at Jenkins version 1.587

**Comment by cmoro-deusto** [comment]
Confirmed on 1.580.2 as well.

**Comment by rtgibbons** [comment]
FWIW, this looks to be fixed on Master

**Comment by elferink** [comment]
Problem hasn't changed for me with the latest theme.js and css

**Comment by rtgibbons** [comment]
> FWIW, this looks to be fixed on ~~Master~~ develop

Type, fixed original

**Comment by elferink** [comment]
Yes it does seem to be fixed on develop.

**Comment by djonsson** [comment]
Hi,

I´ll start to go through the issues once the test environment is working again. We're having some issues with the ssl cert on test.do at the moment which makes changes hard to test. 

Cheers,

Daniel

**Comment by rtgibbons** [comment]
@djonsson I'm willing to lend a helping hand if needed. Just let me know.

**Comment by djonsson** [comment]
Develop now merged.
