### ISSUE TITLE
footer covering up bottom on page-body

### ISSUE THREAD

**Issue by rtgibbons** [djonsson/jenkins-atlassian-theme#55]
Looks like the page-body isn't being adjusted properly for the fixed footer.

This is noticeable when content reaches the bottom of the page. i.e. configuration and console output screens. Here is an example screenshot

![avbch-be_wltuc8qqmqjpf1jfzktistydcxp19xhfxc](https://cloud.githubusercontent.com/assets/8000/5875765/42b25cf4-a2d6-11e4-89b0-b3e8a8d95ad4.png)

**Comment by rtgibbons** [comment]
BTW, this is on Safari 8 and Chrome Canary 42

**Comment by rtgibbons** [comment]
I think the issue might be `height: 100%!important;` being applied to `.page-body` ([here][1]) and possibly `.row` 

When I remove this from `.page-body` the content flow fixed itself; but there is a horizontal scroll. Removing this from `.row` at the same time; remove the scroll but kept the scrollbar.

So, Adding `overflow-x: hidden` to `.page-body` remove the scroll bar.

I'm not sure the purpose of having the height set to 100%, or what issues will arise out of `overflow-x: hidden`

[1]: https://github.com/djonsson/jenkins-atlassian-theme/blob/master/src/style.css#L10-L12

**Comment by barkingfoodog** [comment]
I adjusted the `#page-body` to `height: 85%!:important;` and that cleaned up the issue for me in Safari 8. Yes, that was a total hack and there's likely more elegant ways to fix this issue, but it worked well enough for my purposes. I don't see any problems with a horizontal scroll appearing.

**Comment by rtgibbons** [comment]
Yeah; it fixes it - but it creates a weird gap when the page is real tall; or contains to cut it off when the page is too short.

I'm running off a branch right now with overflow-x: hidden and it's seems to work well. I submitted the pull request #58 for you to see the diff

**Comment by rtgibbons** [comment]
This might be related to issue #57 , might what to see if the fix being pushed out by [Jenkins in 1.597][1] fixes it

[1]: https://github.com/jenkinsci/jenkins/commit/e2ec9eb3c23a6b4f63c338e634d647486a136f7b?w=1

**Comment by rtgibbons** [comment]
This too was fixed upstream in Jenkins 1.598 (actually there is another issue now with the footer causing too much spacing; not sure if upstream issue or theme :/)
