### ISSUE TITLE
Nested view status bar doesn't work. 

### ISSUE THREAD

**Issue by kuberkaul** [djonsson/jenkins-atlassian-theme#61]
I have nested view which is an option when you create views : 

![screen shot 2015-04-30 at 4 17 08 pm](https://cloud.githubusercontent.com/assets/2179966/7421651/789f73e0-ef54-11e4-9739-93c5501b62cf.png)

But the display bar doesn't show up and just shows repeated @nbsp at http://jenkinsxx.xx.net:7777/view/content/# : 
![screen shot 2015-04-30 at 4 15 15 pm](https://cloud.githubusercontent.com/assets/2179966/7421615/2a5c2a8e-ef54-11e4-85bc-68435ad55fd0.png)

**Comment by kuberkaul** [comment]
@djonsson ping

**Comment by ssbarnea** [comment]
:8ball:

**Comment by djonsson** [comment]
Hi, 

Are you using https://wiki.jenkins-ci.org/display/JENKINS/Nested+View+Plugin ?

**Comment by pysysops** [comment]
I have a pull request in with Jenkins for this: https://github.com/jenkinsci/nested-view-plugin/pull/23

It's because of the output from Jelly escaping html and replacing "&nbsp;" with "&amp;nbsp;". Strangely, some browsers render this fine. Firefox doesn't...
