### ISSUE TITLE
Login Screen different when running theme locally

### ISSUE THREAD

**Issue by boldhawk** [djonsson/jenkins-atlassian-theme#63]
Hey Guys - first this is a great theme. But I have a strange problem where the theme works correctly when I link directly to your hosted css and js. 

However, if I copy the css and js locally, or if I build the release locally, when I logout I see the original black jenkins butler theme on the login page instead of the blue page which seems to work for all other pages.

Thanks

**Comment by KraigM** [comment]
This is because Jenkins requires authorization before you can load static resources.  If you turn on your browser debugger you will see that it can't load the files (unless it has recently been cached by your browser).

**Comment by boldhawk** [comment]
Thanks Kraig

I thought this might be the case. So I am better off putting the content
remotely and linking to it than having it locally on the jenkins server?

Thanks

Jon

**Comment by djonsson** [comment]
Hmm, didn't know that Jenkins worked like that. Looks like it's better to link to the remote files.
