### ISSUE TITLE
Hosted release unavailable?

### ISSUE THREAD

**Issue by mmehra** [djonsson/jenkins-atlassian-theme#66]
http://master.source.test.do/dist/theme.css

Not able to reach above anymore

**Comment by gionn** [comment]
It looks like that the test.do domain is expired.

```
Nombre Dominio :
TEST.DO
Titular del Dominio :
Devloop AB
Contacto Administrativo :
Tony Lentino
Contacto Técnico :
Tony Lentino
Contacto Facturación :
Tony Lentino
Fecha de Registro :
18 de Septiembre del 2013
Fecha de Expiración :
18 de Septiembre del 2015
Servidores DNS :

clay.ns.cloudflare.com
daisy.ns.cloudflare.com
```

**Comment by djonsson** [comment]
We will move the hosting from the hosted release during this week. Sorry about the inconvenience.

**Comment by djonsson** [comment]
As a workaround, you can use these urls for now: 

http://109.74.7.228/master/dist/theme.css
http://109.74.7.228/master/dist/theme.js

**Comment by mmehra** [comment]
Closing the issue as the original hosted release is back

**Comment by kansasSamurai** [comment]
FWIW, this appears to still be broken (though the workaround links work).  
p.s.  Given that this is such a straight forward project, I was able to simply "build" each file from the command line like the following (it appeared to work):  
cat *.js > theme.js
cat *.css > theme.css

I had to take that approach (before I stumbled on this issue/post) because the node.js install was broken for debian wheezy.

**Comment by gionn** [comment]
Still down, see also #67

**Comment by gionn** [comment]
I forgot about this until today, [workaround](https://github.com/djonsson/jenkins-atlassian-theme/issues/66#issuecomment-142021864) server is not responding anymore.

Links in the README are still down, probably they never worked.

@mmehra @djonsson

**Comment by djonsson** [comment]
They used to work but got closed down today as the server was killed, I will look into cheaper hosting!

**Comment by gionn** [comment]
You can use github pages! https://pages.github.com/

**Comment by mmehra** [comment]
Temporary links seem to be working for me

**Comment by gionn** [comment]
@mmehra 
http://downforeveryoneorjustme.com/109.74.7.228
http://downforeveryoneorjustme.com/master.source.test.do

Can't reach that ip, and dns resolution for master.source.test.do doesn't work too.

Maybe they are working only on your corporate network and not on the internet?

**Comment by djonsson** [comment]
@gionn now it's hosted on github pages instead!

**Comment by gionn** [comment]
@djonsson great, but prefer the usage of http://djonsson.github.io/jenkins-atlassian-theme/theme.css and so on, since the http headers are more cache-friendly, instead of rawgit endpoint.

**Comment by mmehra** [comment]
Thanks @djonsson. Can you also update README with new links?

**Comment by djonsson** [comment]
@mmehra you can find the links under "hosted installation"
