### ISSUE TITLE
Screenshot on documentation

### ISSUE THREAD

**Issue by agonzalezro** [djonsson/jenkins-atlassian-theme#71]
Hi!

This is a request out of the blue but I was looking for themes for Jenkins and I end up here. Before deciding to install the theme it would be nice to see how it looks.

Thanks!

**Comment by djonsson** [comment]
Hi,

I'd rather not add a screenshot as it would require me to update it between every release. As a hosted version of the theme is provided, it's quite easy to demo it.

**Comment by ipedrazas** [comment]
But then, if I want to see how it looks like... how do I do it?

**Comment by djonsson** [comment]
Follow the installation instructions. If you don't want to do this on a live instance, you can always start a local instance and try it out. Take ~5 -10 minutes: https://wiki.jenkins-ci.org/display/JENKINS/Installing+Jenkins
