### ISSUE TITLE
How about a preview of the theme?

### ISSUE THREAD

**Issue by shellscape** [djonsson/jenkins-atlassian-theme#73]
Would be great to have a couple of screenshots of this theme so those not familiar with it can take a peek before doing the leg work.

**Comment by Ramblurr** [comment]
+1

**Comment by ccelebi** [comment]
+1

**Comment by jlndk** [comment]
+1

**Comment by rtgibbons** [comment]
Hey everyone, check out https://jenkins-atlassian-theme.herokuapp.com/

This is a base install with the required modules, and two jobs setup to see their failure / output. I've locked it down (I hope) to where anonymous is pretty much read-only and can only build jobs. Please try to poke some holes into and let me know -- also if you think there should be a permission for something that's not there, let me know.

@djonsson let me know what you think about this, and if you want to push this to the main docks / merge into this git repo.

**Comment by djonsson** [comment]
Hi @rtgibbons 

Thanks for the work! I think it's a really good idea. Feel free to include the link somewhere in the top of the readme and do a pull request. 

However, please don't link the cdn version of the theme as hey are cached and will not expire when the theme is updated:
https://cdn.rawgit.com/djonsson/jenkins-atlassian-theme/gh-pages/theme.js
https://cdn.rawgit.com/djonsson/jenkins-atlassian-theme/gh-pages/theme-min.css

Instead, use these for now:
https://rawgit.com/djonsson/jenkins-atlassian-theme/gh-pages/theme.js
https://rawgit.com/djonsson/jenkins-atlassian-theme/gh-pages/theme-min.css

In the future my plan is to deploy versioned css and js and update the readme for each version, but it's not done yet. 

Thanks!

/Daniel
