### ISSUE TITLE
Credentials Icon is bigger than other Icons

### ISSUE THREAD

**Issue by flippingtables** [djonsson/jenkins-atlassian-theme#75]
In Chrome 48 on Windows 7 and Jenkins 1.652.
The Jenkins Credentials Icon is larger than all other icons. 

See screenshot below:
![chrome_2016-03-14_12-29-44](https://cloud.githubusercontent.com/assets/1615244/13743181/861216ea-e9e0-11e5-9426-e209f1b0a748.png)

**Comment by djonsson** [comment]
Hi,

These icons are not default in the standard jenkins atlassian theme. I guess you have some changes in your fork.
