### ISSUE TITLE
Jenkins 2.0, Job configure Screen: Gap between tabbar and settings

### ISSUE THREAD

**Issue by schorsch3000** [djonsson/jenkins-atlassian-theme#78]
Hi,
i've updated Jenkins to 2.0, the theme seems to work fine except the job-configure-screen.
There is a huge gap between the tabbar and the settings.
I manage to solve this problem with: https://github.com/schorsch3000/jenkins-atlassian-theme/commit/5039f70ee12e4f89227c78f739c139c56e1d3efb 

i don't know if it breaks the theme on jenkins 1.x how should we manage this?

**Comment by djonsson** [comment]
Hi,

I'll test your change on Jenkin 1.x and apply the change if it looks good!

**Comment by djonsson** [comment]
Fixed in https://github.com/djonsson/jenkins-atlassian-theme/commit/ac8afc2e0393927e0f62eda22ab0474982905b11

**Comment by schorsch3000** [comment]
Nice, thanks!
